name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - python=3.11
  - r-shiny
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - toolz
  - matplotlib
  - pandas
  - pip
  - pip:
    - scikit-learn
    - numpy
